### ISSUE TITLE
Implement MySQL storage

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#11]
Store and read metrics from MySQL table:

```sql
CREATE TABLE `features_metrics` (
 `entry_id` int(9) NOT NULL AUTO_INCREMENT,
 `feature` varchar(32) NOT NULL,
 `metric` varchar(32) NOT NULL,
 `value` int(9) NOT NULL,
 `timestamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`entry_id`),
 KEY `feature_metric_timestamp_idx` (`feature`, `metric`, `timestamp`)
) CHARACTER SET utf8;
```

> * https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html
> * https://dev.mysql.com/doc/refman/5.7/en/datetime.html

## Config

```yaml
storage:
  engine: mysql
  host: "mike-db.prod"
  database: "mike_holmes"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
```
