### ISSUE TITLE
Support variables substitution in YAML config file

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#2]
See https://github.com/macbre/optimist-config-file/pull/5 and https://docs.docker.com/compose/compose-file/#variable-substitution

```yaml
# assuming JIRA_USER and JIRA_PASSWORD env variables are set
sources:
  - name: wikia/jira
    kind: common/jira
    host: "the-company.attlasian-inc.com"
    user: "${JIRA_USER}"  # variables substitution
    password: "${JIRA_PASSWORD}" # Jira API key
```
