### ISSUE TITLE
Allow features to have label customised via template values 

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#31]
```yaml
metrics:
  # Google Analytics
  - name: analytics/events
    source: wikia/analytics
    label: "{ga_label}: %d"
    metric: "ga:totalEvents"
    filters: "{ga_filter}"

features:
  - name: CKEditor
    url: http://docs.company.net/pages/CKEditor
    repo: https://github.com/Wikia/app/tree/dev/extensions/wikia/RTE
    template:
        component: "CK Editor (RTE)"
        ga_filter: "ga:eventCategory==editor-ck;ga:eventAction==submit;ga:eventLabel==publish"
        ga_label: "Edits published"
    metrics:
        - name: analytics/events
```
