### ISSUE TITLE
Add http/json source

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#39]
Add an ability to fetch metrics from JSON-formatted HTTP responses.

### Config

```yaml
sources:
  - name: foo/http
    kind: http/json
    http_proxy: "localhost:8080" # optional parameter

#

metrics:
  - name: wikipedia/stats
    source: http/json  # let's use the base source directly here
    url: "https://{wikipedia_domain}.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=statistics&format=json"
    jq: ".query.statistics.{stats_field}"
    label: "{wikipedia_domain} Wikipedia {stats_field}: %d"

# 

features:
  - name: PolishWikipedia
    template:
      - wikipedia_domain: "pl"
      - stats_field: "articles"
    metrics:
      - name: wikipedia/stats
```

### Request's example

```json
$ curl -s https://elecena.pl/stats.json | jq '.stats.products'
"4 732 522"

$ curl -s 'https://pl.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=statistics&format=json' | jq '.query.statistics.articles'
1317263

$ curl -s 'https://api.github.com/repos/Wikia/Mike' | jq '.stargazers_count'
3
```

* allow to provide [`jq`-like query](https://stedolan.github.io/jq/manual/#Basicfilters) to extract a specific value from JSON response - https://pypi.org/project/pyjq/
* remove spaces to get proper numeric values
