### ISSUE TITLE
Implement Jira source

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#4]
## `source` config

```yaml
  - name: wikia/jira
    kind: common/jira
    host: "the-company.attlasian-inc.com"
    user: "${JIRA_USER}"  # variables substitution
    password: "${JIRA_PASSWORD}" # Jira API key
```

## `metrics` config

```yaml
  - name: jira/p3-tickets
    source: wikia/jira  # see above
    query: "project = '{project}' AND Priority = 'P3' AND status = 'Open'"  # you can use template strings
    label: "%d P3 tickets"
```
