### ISSUE TITLE
Float values are not handled by Mike

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#40]
```
mycroft_holmes.errors.MycroftSourceError: Failed to get metric value: ValueError("invalid literal for int() with base 10: '42.857142857142854'")
```

## Config

```yaml
sources:
  - name: foo/analytics
    kind: common/analytics
    credentials: '${ANALYTICS_SERVICE_ACCOUNT_JSON}'
    view_id: ${ANALYTICS_FOO}

metrics:
  - name: foo/bounce_rate
    source: foo/analytics
    label: "Bounce rate: %d%"
    metric: "ga:bounceRate"
    filters: ""
```
