### ISSUE TITLE
"filters" option should be optional for metrics of type "common/analytics"

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#41]
```yaml
metrics:
  - name: foo/bounce_rate
    source: foo/analytics
    label: "Bounce rate: %d%"
    metric: "ga:bounceRate"
    filters: ""
```
