### ISSUE TITLE
Provide docker-compose.yaml example and a simple yet working example.yaml

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#56]
Make `example.yaml` work without any credentials setup required. Use `http/json` source and read Wikipedia stats?

## `docker-compose.yaml`

```yaml
version: '2'
services:
  mike:
    image: macbre/mike:latest
    volumes:
      # config and dot env files
      #- ./macbre.yaml:/etc/macbre/macbre.yaml
      #- ./.env:/opt/mike/.env
    ports:
    - "5000:5000"
    environment:
    #- MIKE_CONFIG=/etc/macbre/macbre.yaml
    - DATABASE_PASSWORD=m1k4
    depends_on:
    - db
    restart: always

  # metrics storage
  db:
    image: mysql:8.0
    volumes:
      - ./datadir:/var/lib/mysql 
    environment:
    # https://hub.docker.com/_/mysql
    - MYSQL_ROOT_PASSWORD=e4e3065f12a841343997bb2bb4797fdbdc612c91
    - MYSQL_DATABASE=mike
    - MYSQL_USER=mike
    - MYSQL_PASSWORD=m1k4
```
