### ISSUE TITLE
Add http/xpath source

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#59]
Add an ability to fetch metrics from HTML parsed using xpath queries.

> See #39 for a similar source

### Config

```yaml
metrics:
  - name: lubimy_czytac/rating
    source: http/xpath  # let's use the base source directly here
    url: "http://lubimyczytac.pl/ksiazka/{book_id}"
    xpath: '//*[@itemprop="aggregateRating"]//*[@itemprop="ratingValue"]'
    label: "Book rating: %d"

# 

features:
  - name: FarerskieKadry
    template:
      - book_id: 4871910
    metrics:
      - name: lubimy_czytac/rating
```

### Request's example

Extract [ratings from lubimyczytac.pl](http://lubimyczytac.pl/ksiazka/4871910/farerskie-kadry-wyspy-gdzie-owce-mowia-dobranoc):

```
document.evaluate('//*[@itemprop="aggregateRating"]//*[@itemprop="ratingValue"]', document).iterateNext()
<span itemprop=​"ratingValue">​8​</span>​
```
