### ISSUE TITLE
Implement features score thresholds

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#60]
![legacy components mike](https://user-images.githubusercontent.com/1929317/52274315-9aa0e600-294c-11e9-85c4-fa24366534e3.png)

Render features widgets with a proper "priority" icon based on their scores and set up threshold - see https://wikia.github.io/Mike/ for examples.

```yaml
thresholds:
  mayor: 50000  # features with scores greater than this value will have a yellow "card-header-warning" icon
  critical: 200000  # features with scores greater than this value will have a red "card-header-danger" icon
```
