### ISSUE TITLE
features: "url" and "repo" are not required attributes, do not render them if they are not provided

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#62]
Examples

```yaml
features:
  - name: DynamicPageList
    url: http://docs.company.net/pages/DynamicPageList
    repo: https://github.com/Wikia/app/tree/dev/extensions/DynamicPageList
```

vs

```yaml
features:
  - name: FooBar
```
