### ISSUE TITLE
Introduce percentage metric

### ISSUE THREAD

**Issue by macbre** [Wikia/Mike#69]
Its value will be calculated from two different metrics:

```yaml
  - name: SourceEditor
    url: http://docs.company.net/pages/SourceEditor
    repo: https://github.com/Wikia/app
    template:
        component: "Source Editor"
        ga_category: "editor-mw"
    metrics:
        - name: editor/impressions
        - name: editor/publishes
        # percentage
        - name: editor/success_ratio
          type: percentage
          value: editor/publishes  # percentage of publishes compared to all impressions
          of: editor/impressions  # this is 100%
```
